[build]
  command = "npm ci && npm run build"
  publish = "dist"

[context."hardening"]
  command = "HARDENING=1 npm ci && npm run build && cp ./template_contextualising.html ./dist/ && cp ./1_the_individual_tokenised.html ./dist/"

# (keep your headers as-is)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy-Report-Only = "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'; img-src 'self' data: blob: https:; font-src 'self' https:; style-src 'self' 'unsafe-inline'; connect-src 'self' https:; script-src 'self'; upgrade-insecure-requests"
    X-Robots-Tag = "noindex, nofollow"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
