[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Global security headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options    = "nosniff"
    Referrer-Policy           = "strict-origin-when-cross-origin"
    Permissions-Policy        = "geolocation=(), camera=(), microphone=()"
    X-Frame-Options           = "DENY"

    # CSP (single line — no backslashes)
    # - scripts: only this site
    # - styles: this site + inline + Google Fonts CSS
    # - fonts: this site + data: + Google Fonts static
    # - images: this site + data: + S3 (if your docs embed S3 images)
    # - connect: this site (Netlify Functions are same-origin)
    # - block plugins/frames, restrict base URI
    Content-Security-Policy = "default-src 'self'; connect-src 'self'; img-src 'self' data: https://*.amazonaws.com; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; object-src 'none'; frame-ancestors 'none'; base-uri 'self'"
