# netlify.toml (minimal, styling-friendly)

[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options   = "nosniff"
    Referrer-Policy          = "strict-origin-when-cross-origin"
    Permissions-Policy       = "geolocation=(), microphone=(), camera=()"
# NOTE: No CSP here. If you later want one, we can add a relaxed CSP that
# still allows inline styles and the Netlify Identity script.
