[build]
  command = "npm ci && npm run build"
  publish = "dist"

# If you want a branch-specific build
[context."hardening"]
  command = "HARDENING=1 npm ci && npm run build"

# Security headers (this file only exists in your hardening branch)
[[headers]]
  for = "/*"
  [headers.values]
    # Start report-only so you can see violations without breaking the UI
    Content-Security-Policy-Report-Only = "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'; img-src 'self' data: blob: https:; font-src 'self' https:; style-src 'self' 'unsafe-inline'; connect-src 'self' https:; script-src 'self'; upgrade-insecure-requests"

    # Don’t let this preview be indexed
    X-Robots-Tag = "noindex, nofollow"

    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
